"""
Purpose: Package marker for curtain_bridge.fixtures.templates, holding the
         two reference template PNGs (filevault_prompt.png,
         login_window.png) that curtain_bridge.detection.detect_state()
         matches captured frames against.
Inputs: none (package marker).
Outputs: none.
Constraints: both PNGs are SYNTHETIC placeholders generated by a one-off
             Pillow script (not checked in -- see CHANGELOG.md), standing in
             for real macOS FileVault/login-window screenshots. They are NOT
             real hardware captures. Real accuracy tuning against an actual
             TinyPilot HDMI capture is deferred until that hardware is
             purchased -- see detection.py's module docstring and
             CHANGELOG.md for the exact variables (resolution/scaling/
             color-profile/frame-rate) that still need verification.
SPORT: MASTER-APPS (Bridge/ deployment artifact, T-P1-E12-01)
"""
