"""
Purpose: Tests for curtain_bridge.detection -- confirms detect_state()
         performs real cv2.matchTemplate calls against the checked-in
         reference templates (not a stub) with true-positive results for
         both target states and true-negative results against several
         non-target fixtures, and that VideoMonitorModule's polling loop is
         correctly wired to the detection function with no busy-loop CPU
         waste.
Inputs: none (fixtures loaded from tests/fixtures/*.png -- synthetic
        composites generated by a one-off Pillow script, not real macOS
        screenshots; see tests/fixtures/README.md and CHANGELOG.md for the
        explicit hardware-verification-still-needed flag).
Outputs: pytest test functions.
Constraints: exercises the real OpenCV template-matching path end-to-end
             (no mocking of cv2.matchTemplate itself) -- these tests ARE the
             evidence that matching actually works, not code inspection.
SPORT: MASTER-APPS (Bridge/ deployment artifact, T-P1-E12-01)
"""

from __future__ import annotations

import asyncio
import io
import math
from importlib import resources
from pathlib import Path

import cv2
import numpy as np
import pytest
from PIL import Image

from curtain_bridge.detection import (
    CONFIDENCE_THRESHOLD,
    POLL_INTERVAL_SECONDS,
    DetectionResult,
    DetectionState,
    VideoMonitorModule,
    _best_match_score,
    detect_state,
)

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _load(name: str) -> bytes:
    return (FIXTURES_DIR / name).read_bytes()


# -- true positives -------------------------------------------------------------


def test_detects_filevault_prompt_full_frame():
    result = detect_state(_load("filevault_prompt_full.png"))
    assert result.state == DetectionState.FILEVAULT_PROMPT
    assert result.confidence >= CONFIDENCE_THRESHOLD


def test_detects_login_window_full_frame():
    result = detect_state(_load("login_window_full.png"))
    assert result.state == DetectionState.LOGIN_WINDOW
    assert result.confidence >= CONFIDENCE_THRESHOLD


def test_detects_logged_in_desktop_full_frame():
    # T-P1-E12-03: third detection state, distinct from FILEVAULT_PROMPT and
    # LOGIN_WINDOW -- positively confirms the Mac reached the unlocked
    # desktop rather than the HID-typing flow assuming success.
    result = detect_state(_load("logged_in_desktop_full.png"))
    assert result.state == DetectionState.LOGGED_IN_DESKTOP
    assert result.confidence >= CONFIDENCE_THRESHOLD


def test_detection_result_is_correct_type():
    result = detect_state(_load("filevault_prompt_full.png"))
    assert isinstance(result, DetectionResult)
    assert isinstance(result.state, DetectionState)
    assert isinstance(result.confidence, float)


# -- true negatives ---------------------------------------------------------------


def test_plain_desktop_is_no_match():
    # Regression guard specific to the LOGGED_IN_DESKTOP addition:
    # plain_desktop.png already contains generic menu-bar/dock chrome (two
    # plain rectangles + a dock with solid-color squares) that must NOT be
    # confused with LOGGED_IN_DESKTOP's distinguishing Control-Center-pill +
    # battery-glyph template -- it must still classify as NO_MATCH, not a
    # false positive for either state.
    result = detect_state(_load("plain_desktop.png"))
    assert result.state == DetectionState.NO_MATCH
    assert result.confidence < CONFIDENCE_THRESHOLD


def test_screensaver_is_no_match():
    result = detect_state(_load("screensaver.png"))
    assert result.state == DetectionState.NO_MATCH
    assert result.confidence < CONFIDENCE_THRESHOLD


def test_app_dialog_is_no_match():
    # Confirms generic rounded-rect dialog chrome (buttons, panel) does not
    # false-positive against either the padlock or avatar-circle templates.
    result = detect_state(_load("app_dialog.png"))
    assert result.state == DetectionState.NO_MATCH
    assert result.confidence < CONFIDENCE_THRESHOLD


def test_negative_fixtures_score_meaningfully_below_threshold():
    # Regression guard: true-negative scores should sit clearly below
    # threshold, not just barely under it (which would suggest the fixtures
    # are accidentally near-duplicates of the templates).
    for name in ("plain_desktop.png", "screensaver.png", "app_dialog.png"):
        result = detect_state(_load(name))
        assert result.confidence < CONFIDENCE_THRESHOLD - 0.1, (
            f"{name} scored {result.confidence:.3f}, too close to threshold "
            f"{CONFIDENCE_THRESHOLD} for a confident true-negative"
        )


def test_filevault_and_login_window_are_not_confused_with_logged_in_desktop():
    # Cross-state true-negative: the FileVault/login-window full frames must
    # not false-positive against the new LOGGED_IN_DESKTOP template either.
    filevault_result = detect_state(_load("filevault_prompt_full.png"))
    assert filevault_result.state != DetectionState.LOGGED_IN_DESKTOP

    login_result = detect_state(_load("login_window_full.png"))
    assert login_result.state != DetectionState.LOGGED_IN_DESKTOP


def test_logged_in_desktop_is_not_confused_with_filevault_or_login_window():
    result = detect_state(_load("logged_in_desktop_full.png"))
    assert result.state not in (DetectionState.FILEVAULT_PROMPT, DetectionState.LOGIN_WINDOW)


# -- no vision-model/LLM dependency -----------------------------------------------


def test_detection_module_imports_no_llm_or_http_client():
    # Static guard against scope creep: detection.py must never import an
    # HTTP client or LLM SDK for classification -- only cv2/numpy/PIL.
    import curtain_bridge.detection as detection_module

    source = Path(detection_module.__file__).read_text()
    forbidden_tokens = ["httpx", "openai", "anthropic", "requests"]
    for token in forbidden_tokens:
        assert token not in source, f"detection.py must not reference {token!r}"


# -- polling loop (VideoMonitorModule) ---------------------------------------------


class _FakeTinyPilotClient:
    """Stand-in for TinyPilotClient -- returns a fixed screenshot payload on
    every get_screenshot() call and counts invocations, without touching the
    network or importing tinypilot_client.py's httpx dependency."""

    def __init__(self, screenshot_bytes: bytes | None) -> None:
        self._screenshot_bytes = screenshot_bytes
        self.call_count = 0

    def get_screenshot(self) -> bytes | None:
        self.call_count += 1
        return self._screenshot_bytes


@pytest.mark.asyncio
async def test_video_monitor_polls_and_invokes_callback():
    client = _FakeTinyPilotClient(_load("filevault_prompt_full.png"))
    received: list[DetectionResult] = []

    async def on_detection(result: DetectionResult) -> None:
        received.append(result)

    module = VideoMonitorModule(client, on_detection)
    await module.start(config=None)  # type: ignore[arg-type]
    try:
        # First poll fires immediately (no pre-sleep before the first
        # capture), so a short wait is enough to observe at least one call.
        await asyncio.sleep(0.2)
    finally:
        await module.stop()

    assert client.call_count >= 1
    assert len(received) >= 1
    assert received[0].state == DetectionState.FILEVAULT_PROMPT


@pytest.mark.asyncio
async def test_video_monitor_continues_after_screenshot_error():
    class _FlakyClient:
        def __init__(self) -> None:
            self.call_count = 0

        def get_screenshot(self) -> bytes | None:
            self.call_count += 1
            if self.call_count == 1:
                raise RuntimeError("simulated transient network failure")
            return _load("plain_desktop.png")

    client = _FlakyClient()
    received: list[DetectionResult] = []

    async def on_detection(result: DetectionResult) -> None:
        received.append(result)

    # Temporarily shrink the poll interval for a fast test -- patched via
    # module attribute rather than sleeping for the real 3s cadence.
    import curtain_bridge.detection as detection_module

    original_interval = detection_module.POLL_INTERVAL_SECONDS
    detection_module.POLL_INTERVAL_SECONDS = 0.05
    try:
        module = VideoMonitorModule(client, on_detection)
        await module.start(config=None)  # type: ignore[arg-type]
        await asyncio.sleep(0.3)
        await module.stop()
    finally:
        detection_module.POLL_INTERVAL_SECONDS = original_interval

    # First call raised and was swallowed+logged; the loop kept going and
    # produced at least one successful classification afterward.
    assert client.call_count >= 2
    assert any(r.state == DetectionState.NO_MATCH for r in received)


@pytest.mark.asyncio
async def test_video_monitor_stop_is_safe_without_start():
    client = _FakeTinyPilotClient(None)

    async def on_detection(_: DetectionResult) -> None:
        pass

    module = VideoMonitorModule(client, on_detection)
    await module.stop()  # must not raise


@pytest.mark.asyncio
async def test_video_monitor_skips_none_screenshot():
    # get_screenshot() returns None on TinyPilot's 204 No Content (no video
    # input) -- the poll loop must skip calling detect_state()/the callback
    # for that tick rather than erroring.
    client = _FakeTinyPilotClient(None)
    received: list[DetectionResult] = []

    async def on_detection(result: DetectionResult) -> None:
        received.append(result)

    module = VideoMonitorModule(client, on_detection)
    await module.start(config=None)  # type: ignore[arg-type]
    await asyncio.sleep(0.2)
    await module.stop()

    assert client.call_count >= 1
    assert received == []


# -- NaN/degenerate-frame guard -----------------------------------------------


def test_best_match_score_is_finite_for_uniform_frame():
    # Regression guard: a near-zero-variance frame (e.g. solid black/gray
    # right after an HDMI lock) can make TM_CCOEFF_NORMED's normalization
    # denominator go to ~zero and produce NaN entries in matchTemplate's
    # result matrix. _best_match_score must sanitize those away rather than
    # letting a NaN win minMaxLoc's max and propagate into detect_state()'s
    # tie-break loop (which would otherwise fall through to its "unreachable"
    # AssertionError, per detection.py's docstring on this fix).
    frame_bgr = np.full((800, 1280, 3), 128, dtype=np.uint8)

    template_bytes = (
        resources.files("curtain_bridge.fixtures.templates")
        .joinpath("filevault_prompt.png")
        .read_bytes()
    )
    template_rgb = np.array(Image.open(io.BytesIO(template_bytes)).convert("RGB"))
    template_bgr = cv2.cvtColor(template_rgb, cv2.COLOR_RGB2BGR)

    score = _best_match_score(frame_bgr, template_bgr)
    assert math.isfinite(score)
    assert not math.isnan(score)


def test_detect_state_handles_uniform_frame_without_raising():
    # End-to-end version of the guard above, through detect_state() itself --
    # confirms the whole classification path (not just _best_match_score) is
    # safe against a degenerate frame, with no AssertionError and a clean
    # NO_MATCH-shaped result (finite confidence, valid DetectionState).
    height, width = 800, 1280
    frame = np.full((height, width, 3), 128, dtype=np.uint8)
    buf = io.BytesIO()
    Image.fromarray(frame).save(buf, format="PNG")

    result = detect_state(buf.getvalue())

    assert isinstance(result, DetectionResult)
    assert isinstance(result.state, DetectionState)
    assert math.isfinite(result.confidence)


def test_poll_interval_and_threshold_are_documented_constants():
    # Regression guard against ever inlining these as magic numbers at call
    # sites -- both must remain named, importable module constants.
    assert isinstance(CONFIDENCE_THRESHOLD, float)
    assert 0.0 < CONFIDENCE_THRESHOLD <= 1.0
    assert isinstance(POLL_INTERVAL_SECONDS, float)
    assert POLL_INTERVAL_SECONDS > 0.0
